[EW] Added basic Jenkins Stub functionality
eledg/jenkins-stub pull request #1
Opened 2021-02-01 11:22 UTC by EWright213

2021-02-01 12:39 UTC, eledg requested changes

2021-02-01 12:39 UTC, eledg commented on src/JenkinsStub.kt
> +                    call.respondText(status = HttpStatusCode.OK) { "" }
This can just be `call.respond(HttpStatusCode.OK)`

2021-02-01 12:39 UTC, eledg commented on src/JenkinsStub.kt
> +                val jobParams = "GOOD_PARAM"
Is this variable used?

2021-02-01 12:39 UTC, eledg commented on src/JenkinsStub.kt
> +            route("/$jenkinsUrl/job/job-name-with-params/buildWithParameters") {
You can have multiple routes, so don't need to define `jenkinsUrl` as a variable, e.g.
```
route("jenkins-url") {
    route("job/job-name") {
        // do something
    }
}
```

Having said that, I don't think `jenkins-url` is needed as part of this? Is it part of the api path for a jenkins instance?

2021-02-01 14:07 UTC, EWright213 commented on src/JenkinsStub.kt
> +                    call.respondText(status = HttpStatusCode.OK) { "" }
Fixed, thanks!

2021-02-01 14:07 UTC, EWright213 commented on src/JenkinsStub.kt
> +                val jobParams = "GOOD_PARAM"
Removed, thanks!

2021-02-01 14:10 UTC, EWright213 commented on src/JenkinsStub.kt
> +            route("/$jenkinsUrl/job/job-name-with-params/buildWithParameters") {
Tidied up as per your example. Yes, I believe that the jenkins-url is needed as the api path, as per https://www.jenkins.io/doc/book/using/remote-access-api/

2021-02-01 14:35 UTC, eledg commented on src/JenkinsStub.kt
> +            route("/$jenkinsUrl/job/job-name-with-params/buildWithParameters") {
I think in that example `JENKINS_URL` is meant to just be the domain of Jenkins. In the case of this stub locally it'd be `http://localhost:8084`. Could you compare this to a known Jenkins instance?

2021-02-01 15:51 UTC, EWright213 commented on src/JenkinsStub.kt
> +            route("/$jenkinsUrl/job/job-name-with-params/buildWithParameters") {
Ah I see, you're right! Fixed, thanks!

2021-02-01 18:05 UTC, eledg requested changes

2021-02-01 18:05 UTC, eledg commented on gradle.properties
> +logback_version=1.2.1
Are these the latest versions?

2021-02-01 18:05 UTC, eledg commented on gradle/wrapper/gradle-wrapper.properties
> +distributionUrl=https\://services.gradle.org/distributions/gradle-6.3-bin.zip
This version could be updated too

2021-02-01 18:05 UTC, eledg commented on src/JenkinsStub.kt
> +        println("Starting routing")
Please can the println be removed. If logging is needed here it should be through the logger.

2021-02-10 13:51 UTC, EWright213 commented on gradle.properties
> +logback_version=1.2.1
Updated, thanks!

2021-02-10 13:51 UTC, EWright213 commented on gradle/wrapper/gradle-wrapper.properties
> +distributionUrl=https\://services.gradle.org/distributions/gradle-6.3-bin.zip
Done, thanks!

2021-02-10 13:51 UTC, EWright213 commented on src/JenkinsStub.kt
> +        println("Starting routing")
Removed, I don't think any logging is needed - would you recommend any?

2021-02-10 18:37 UTC, eledg commented on src/JenkinsStub.kt
> +        println("Starting routing")
Nope, I agree

2021-02-10 18:55 UTC, eledg approved these changes

2021-02-10 18:56 UTC, merged